"""Deployment configuration for the XIAO ESP32-C3 telemetry client."""

WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"
WIFI_CONNECT_TIMEOUT_SECONDS = 20

GATEWAY_IP = "192.168.1.42"
GATEWAY_PORT = 5005

NODE_ID = "XIAO-01"
DEVICE_NAME = "Pump-01"
DEVICE_TYPE = "pump"
SITE = "factory01"
AREA = "process"
LINE = "line01"

SEND_INTERVAL_SECONDS = 3
SIMULATION_DURATION_SECONDS = 3600
SOCKET_TIMEOUT_SECONDS = 5
RETRY_DELAY_SECONDS = 2
SCHEMA_VERSION = 1
